site_name: "SSSOM"
theme: readthedocs
docs_dir: target/docs
site_dir: docs
nav:
  - Home: home.md
  - SSSOM Specification: spec.md
  - Use cases: usecases.md
  - Workshops: workshops.md
  - Presentations: presentations.md
  - Index: index.md
  - Credits: credits.md
  - FAQ: faq.md
